### ISSUE TITLE
Uncaught Error: Class 

### ISSUE THREAD

**Issue by DEVIZ-Dawid-Pogoda** [bluepayment-plugin/bm-sdk#13]
Stworzyłem dla testów index.php w folderze src

```
<?php
require_once 'Client.php';

$client = new BlueMedia\Client(
            'id', 
            'klucz',
            'sha256', 
            '|'
);

```
Po wpisaniu poprawnych parametrów id i klucza błąd:
Uncaught Error: Class  'BlueMedia\Common\Util\EnvironmentRequirements' not found

**Comment by DEVIZ-Dawid-Pogoda** [comment]
Dopiszcie w dokumentacji, że trzeba załadować vendor/autoload.php 
Zdanie twórz obiekt klasy client kieruje że Client.php to plik z wymaganymi klasami. A tym plikiem jest autload.

**Comment by bmmichal** [comment]
Rozszerzyliśmy sekcję "Instalacja" w dokumentacji o konieczność załadowania klas.
