### ISSUE TITLE
Can't use SDK with Laravel 8

### ISSUE THREAD

**Issue by PatryQHyper** [bluepayment-plugin/bm-sdk#14]
Problem 1
    - Root composer.json requires bluepayment-plugin/bm-sdk ^2.0 -> satisfiable by bluepayment-plugin/bm-sdk[2.0.0].
    - bluepayment-plugin/bm-sdk 2.0.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

**Comment by bmmichal** [comment]
guzzle 7.3 i 7.4 has been added to SDK 2.0
