### ISSUE TITLE
HP Fatal error:  Uncaught BlueMedia\\Common\\Exception\\HashNotReturnedFromServerException: No hash received from server! Check your serviceID

### ISSUE THREAD

**Issue by inprogra** [bluepayment-plugin/bm-sdk#18]
Witam,

Jak w temacie. Po problemie z trim on null (aktualizacja pomogła) pojawił się problem w którym przy "przed transakcji" zwracany jest taki komunikat. Secret + id sklepu jest wstawiony z ustawień bm.

Dodam tylko ,że na środowisku dev (tylko id i klucz jest zmieniony) proces przebiega bez problemu.

**Comment by wizu** [comment]
@inprogra mam ten sam problem. Poradziłeś sobie z tym jakoś?

**Comment by inprogra** [comment]
> @inprogra mam ten sam problem. Poradziłeś sobie z tym jakoś?

@wizu Tak, ale to nic po naszej stronie. Support BM coś przestawił w swoich ustawieniach i zaczęło chodzić.

**Comment by Karol-BM** [comment]
W tym przypadku proszę o kontakt z supportem bramki płatności. Sam klient zadziałał poprawnie, nie otrzymaliśmy hasha więc nie możemy procesować dalej response.

**Comment by serwerin** [comment]
Mam ten sam problem po rejestracji serwisu online.
@inprogra pamiętasz może, czy u Ciebie rejestracja serwisu była w formie onboardingu online (przez formularz online), czy umowa podpisana papierowo / elektronicznie?

**Comment by inprogra** [comment]
@serwerin rejestracja była online.
