### ISSUE TITLE
This SDK is incompatible with Blue Media ITN messages

### ISSUE THREAD

**Issue by jacekkow** [bluepayment-plugin/bm-sdk#19]
Blue Media ITN includes `<customerData>` that is part of the hash, which is unsupported here and makes this SDK return "invalid hash" for every ITN notification.

Sample XML with transaction data from Blue Media server after decoding:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<transactionList>
  <serviceID>123456</serviceID>
  <transactions>
    <transaction>
      <orderID>1</orderID>
      <remoteID>AAAAAAAAAA</remoteID>
      <amount>1.50</amount>
      <currency>PLN</currency>
      <gatewayID>106</gatewayID>
      <paymentDate>20220923000000</paymentDate>
      <paymentStatus>SUCCESS</paymentStatus>
      <paymentStatusDetails>AUTHORIZED</paymentStatusDetails>
      <customerData>
        <fName>Jan</fName>
        <lName>Kowalski</lName>
        <streetName>UL.JASNA</streetName>
        <streetHouseNo>6</streetHouseNo>
        <streetStaircaseNo>A</streetStaircaseNo>
        <streetPremiseNo>3</streetPremiseNo>
        <postalCode>10-234</postalCode>
        <city>WARSZAWA</city>
        <nrb>96109010301793218160815294</nrb>
      </customerData>
    </transaction>
  </transactions>
  <hash>9f09009ce77963f93cb6a1f1bbd65f0e204aaa432a25f1be7c343528320512e0</hash>
</transactionList>
```

Given shared key `0000000000000000000000000000000000000000` this SDK hashes the message above to: `3020f1c2f062fd894cf80241e13e19bac8013177d548726ca31fa9824a704b6a` - the hashed string being:
```
123456|1|AAAAAAAAAA|1.50|PLN|106|20220923000000|SUCCESS|AUTHORIZED|0000000000000000000000000000000000000000
```
but Blue Media servers hash the following string:
```
123456|1|AAAAAAAAAA|1.50|PLN|106|20220923000000|SUCCESS|AUTHORIZED|Jan|Kowalski|UL.JASNA|6|A|3|10-234|WARSZAWA|96109010301793218160815294|0000000000000000000000000000000000000000
```
which gives `9f09009ce77963f93cb6a1f1bbd65f0e204aaa432a25f1be7c343528320512e0`.

You can also simply compare
https://github.com/bluepayment-plugin/bm-sdk/blob/master/src/Itn/ValueObject/Itn.php
to
https://github.com/bluepayment-plugin/prestashop-plugin-1.7/blob/master/sdk/src/Model/ItnIn.php
to notice that there are multiple fields missing...

The attached [test.php](https://github.com/bluepayment-plugin/bm-sdk/files/9636106/test.txt) should return "HASH OK!" but for now it returns "WRONG HASH!".

**Comment by bmmichal** [comment]
Problem has been resolved in version 3.3.0.
