### ISSUE TITLE
ReturnURL - nie respektowany?

### ISSUE THREAD

**Issue by ShinJii89** [bluepayment-plugin/bm-sdk#5]
Dodaliście ostatnio zmienną ReturnURL - czy ona działa przy  TESTOWYCH PŁATNOŚCIACH? Bo zamiast na wpisany w tej zmiennej ReturnURL to przekierowuje mnie na link powrotu dodany w panelu bluemedia.
Zmienną wpisuję w tym miejscu:
` $bluemedia_result = $bluemedia_client->doTransactionInit([
                                    'gatewayUrl' => 'https://pay-accept.bm.pl',
                                    'transaction' => [
                                        'orderID' => $bluemedia_control,
                                        'amount' => $bluemedia_price,
                                        'description' => $paytitle,
                                        'gatewayID' => '0',
                                        'currency' => $currency,
                                        'customerEmail' => $userdata['email'],
                                        'customerIP' => $_SERVER['REMOTE_ADDR'],
                                        'returnURL' => $return_page
                                    ]
                                ]);`

**Comment by bmmichal** [comment]
Najnowsza wersja SDK (1.0.3) nie zawiera jeszcze poprawki pod ReturnURLa. @Bart-CS, kiedy można spodziewać się wydania nowej wersji?

**Comment by ShinJii89** [comment]
@bmmichal czyli jednak jest błąd nie po mojej stronie?

**Comment by bmmichal** [comment]
@ShinJii89, wczoraj została wydana nowa wersja SDK - 1.1.0. Zaciągnij ją i daj znać, czy jest ok. ;)

**Comment by ShinJii89** [comment]
@bmmichal z tego co widzę to nowy release wprowadza tylko aktualizację README... więc wątpię, że coś pomoże, ale zaraz sprawdzę :)

EDIT: Niestety nie sprawdzę tego teraz bo znowu mam ten błąd z tego zgłoszenia: https://github.com/bluepayment-plugin/bm-sdk/issues/3
EDIT 2: Wybaczcie, sugerowałem się MASTERem w którym od dawna mieliście returnURL, a composer faktycznie instalował chyba wersję bez tego :) - no nic, mam już najnowszą wersję ale wciąż mam błąd ten co w zgłoszeniu #3

**Comment by ShinJii89** [comment]
Dobra już wiem o co chodzi - jako localhost:8080 nie przyjmowaliście tego parametru i się wszystko wysypywało ;D moglibyście lepszą obsługę błędów zrobić w tej bibliotece i by człowiek wszystko wiedział :)
