### ISSUE TITLE
BlueMedia\Itn\ValueObject\Itn::getPaymentStatusDetails(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by RazorMeister** [bluepayment-plugin/bm-sdk#6]
Przy requeście ITN ze statusem PENDING nie jest wysyłane pole paymentStatusDetails, przez co w klasie BlueMedia\Itn\ValueObject\Itn ma ono wartość null, a getter (getPaymentStatusDetails) do tego pola ma typowanie na string.

**Comment by scardinius** [comment]
podpinam się pod to, kiedy zostanie rozwiązane?

**Comment by scardinius** [comment]
czy ktoś w ogóle zajmuje się tym repozytorium ze strony firmy Blue Media?

**Comment by RazorMeister** [comment]
Obstawiam że nikt. Moje pozostałe 2 issues jak były nietknięte tak dalej są :)

**Comment by Karol-BM** [comment]
Fixed in #17
