### ISSUE TITLE
Niepoprawna długość MessageID

### ISSUE THREAD

**Issue by RazorMeister** [bluepayment-plugin/bm-sdk#7]
### Opis:
Do metod getPaywayList() oraz getRegulationList() wartość pola MessageID jest liczona NIEPOPRAWNIE. Jego długość wynosi 64 a dozwolone są dokładnie 32 znaki. 

### Błędy z panelu BM:
![image](https://user-images.githubusercontent.com/19613420/133883395-28ba548b-592d-4553-914d-461a740cb898.png)
![image](https://user-images.githubusercontent.com/19613420/133883402-6329ca12-6782-440f-9bae-0d686d73597a.png)
![image](https://user-images.githubusercontent.com/19613420/133883405-bea5a177-1b9c-468c-a8d8-4f7e5d37f11a.png)

### Lokalizacja błędu:
Sposób generowania MessageID: `bin2hex(random_bytes(ClientEnum::MESSAGE_ID_LENGTH))`, 
gdzie `ClientEnum::MESSAGE_ID_LENGTH = 32`
Na poniższym screen z dokumentacji funkcji random_bytes() dokładnie widać, że jeśli przekazujemy do niej inta o wartość X i wykonujemy bin2hex() to funkcja zwraca string o długości X * 2.

![image](https://user-images.githubusercontent.com/19613420/133883584-cb84b45b-7a5f-4bcd-a156-09d7742fdb62.png)

Link do dokumentacji random_bytes(): https://www.php.net/manual/en/function.random-bytes.php

**Comment by woduda** [comment]
Zaproponowałem fix w #15

**Comment by Karol-BM** [comment]
Fixed in #17
