### ISSUE TITLE
trim(): Argument #1 ($string) must be of type string, null given

### ISSUE THREAD

**Issue by RazorMeister** [bluepayment-plugin/bm-sdk#8]
### Problem:
Przy przesłaniu waluty płatności jako EUR dostaję taki wyjątek:
`(TypeError(code: 0): trim(): Argument #1 ($string) must be of type string, null given at [...]Transaction\\ValueObject\\Transaction.php:298)`

Pewnie Api BM zwraca jakiś błąd ale SDK sobie z nim nie potrafi poradzić..

**Comment by ShinJii89** [comment]
Mam to samo u jednego klienta, nie wiem dlaczego... z tym, że u niego normalnie PLN jest...

**Comment by Karol-BM** [comment]
Fixed in #17
